### ISSUE TITLE
[BUG] Not able to delete a user

### ISSUE THREAD

**Issue by prajwalnl0** [juspay/hyperswitch-control-center#1083]
Sent a invite to the user "prajwal.nl+2604@juspay.in", and accepted the invite. 
Later from the main account I'm not able to delete the use.

![Image](https://github.com/user-attachments/assets/a50a693e-ceaa-4cc3-a9ec-fb38a710a0da)

**Comment by muditbhutani** [comment]
@prajwalnl0 please close if resolved
