### ISSUE TITLE
[BUG] Global search results are not sorted.

### ISSUE THREAD

**Issue by prajwalnl0** [juspay/hyperswitch-control-center#1131]
When customer email is used in global search the results are not sorted. It would be better if they are sorted in newest to oldest order

![Image](https://github.com/user-attachments/assets/174dcb67-a4d7-40b1-a4a1-3b03ed2cb9c9)

![Image](https://github.com/user-attachments/assets/793a7b8c-bf52-401f-b31f-9e9a99a8cd2e)

The first two results are the payments done in Jul 18 and 19 even if the latest payment for this customer email is on Aug 8th.

![Image](https://github.com/user-attachments/assets/6bcc2dde-6ba4-4f1f-a0d2-7f04a8c6315c)

![Image](https://github.com/user-attachments/assets/3e9a46f6-c4fc-4e96-972c-e70d513644e2)

**Comment by ShivanshMathurJuspay** [comment]
Sure
This can be taken care of by inducing the sort while sending request to DataSource
