### ISSUE TITLE
[FEATURE] Improved left navigation

### ISSUE THREAD

**Issue by muditbhutani** [juspay/hyperswitch-control-center#1358]
**📝 Feature Description**
In [HS control center ](https://github.com/juspay/hyperswitch-control-center), the left navigation design needs to be modified to become more modern

**🔨 Possible Implementation**
Modify the way sub headings are opened in the navigation. Move developer pages at the bottom with a separate heading of their own

**Submission Process:**
Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
Once assigned, submit a pull request (PR).
Maintainers will review and provide feedback, if any.
Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).
Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by Vaibhav91one** [comment]
Hi @muditbhutani, Please assign this issue to me.
