### ISSUE TITLE
API response structure for payment module

### ISSUE THREAD

**Issue by sagarnaikjuspay** [juspay/hyperswitch-control-center#1426]
### **Payments Processed**
<pre>
{
  "queryData": [
    {"count": 24, "amount": 952, "time_bucket": "2024-08-13 18:30:00"},
    {"count": 28, "amount": 1020, "time_bucket": "2024-08-14 18:30:00"},
    {"count": 35, "amount": 1450, "time_bucket": "2024-08-15 18:30:00"},
    {"count": 30, "amount": 1150, "time_bucket": "2024-08-16 18:30:00"},
    {"count": 40, "amount": 1600, "time_bucket": "2024-08-17 18:30:00"},
    {"count": 29, "amount": 1200, "time_bucket": "2024-08-18 18:30:00"},
    {"count": 31, "amount": 1300, "time_bucket": "2024-08-19 18:30:00"},
  ],
  "metaData": [{"count": 217, "amount": 8672}],
}
</pre>

### **Payments Lifecycle**
<pre>
{
  "normal_success": value,
  "normal_failure": value,
  "cancelled": value,
  "smart_retried_success": value,
  "smart_retried_failure": value,
  "pending": value,
  "failed": value,
  "refunded": value,
  "disputed": value,
  "partial_refunded": value,
  "mandated_payments": value,
  "attempted_pending": value,
  "pm_awaited": value,
  "customer_awaited": value,
}
</pre>

To calculate intermediate nodes
Success -> normal success + smart retry success
Failure -> normal failure + smart retry failure
Refunded -> refunded
Partially refunded -> partially refunded
Pending -> Attempted Pending
Cancelled -> Cancelled
Dropoff2 -> Customer Awaited
Attempted Payments -> Attempted Pending + Customer Awaited + Success + Failure
Dropoff1 -> PM Awaited
Total Payments -> Dropoff1 + Attempted Payments + Cancelled

### **Payments Success Rate**
<pre>
{
  "queryData": [
    {"payments_success_rate": 40, "time_bucket": "2024-08-13 18:30:00"},
    {"payments_success_rate": 35, "time_bucket": "2024-08-14 18:30:00"},
    {"payments_success_rate": 60, "time_bucket": "2024-08-15 18:30:00"},
    {"payments_success_rate": 70, "time_bucket": "2024-08-16 18:30:00"},
    {"payments_success_rate": 75, "time_bucket": "2024-08-17 18:30:00"},
    {"payments_success_rate": 65, "time_bucket": "2024-08-18 18:30:00"},
    {"payments_success_rate": 50, "time_bucket": "2024-08-19 18:30:00"},
  ],
  "metaData": [{"payments_success_rate": 50}],
}
</pre>

### **Successful Payments Distribution**
request
<pre>
{
  groupBy:["connector"]
}
</pre>

<pre>
{
  "queryData": [
    {"payments_success_rate": 40, "connector": "stripe"},
    {"payments_success_rate": 60, "connector": "adyen"},
    {"payments_success_rate": 75, "connector": "paypal"},
    {"payments_success_rate": 65, "connector": "checkout"},
  ],
  "metaData": null,
}
</pre>

### **Failed Payments Distribution**
<pre>
{
  "queryData": [
    {"payments_failure_rate": 40, "connector": "stripe"},
    {"payments_failure_rate": 60, "connector": "adyen"},
    {"payments_failure_rate": 75, "connector": "paypal"},
    {"payments_failure_rate": 65, "connector": "checkout"},
  ],
  "metaData": null,
}
</pre>

### **Failure Reasons**
request 
<pre>
{
  "groupByNames": ["connector"],
  "distribution": {
    "distributionFor": "payment_error_message",
  },
}
</pre>

response 
<pre>
[
  {
    "reason": "No error message",
    "count": 4,
    "percentage": 66.67,
    "connector": "stripe",
  },
  {
    "reason": "The payment failed.",
    "count": 2,
    "percentage": 33.33,
    "connector": "checkout",
  },
]

</pre>

**Comment by tsdk02** [comment]
Updated Response Structures for the Metrics:

Payments Processed: 
- Query Data: 
  - payment_processed_amount
  - payment_processed_count
  - payment_processed_amount_without_smart_retries
  -  payment_processed_count_without_smart_retries
  - time_bucket
- Meta Data:
  - total_payment_processed_amount
  - total_payment_processed_count
  - total_payment_processed_amount_without_smart_retries
  - total_payment_processed_count_without_smart_retries

Payment Success Rate:
- Query Data:
  - successful_payments
  - successful_payments_without_smart_retries
  - total_payments
  - payments_success_rate
  - payments_success_rate_without_smart_retries
  - time_bucket
- Meta Data:
  - total_success_rate
  - total_success_rate_without_smart_retries

Smart Retried Amount:
- Query Data:
  - smart_retried_amount
  - smart_retried_amount_without_smart_retries
- Meta Data:
  - total_smart_retried_amount
  - total_smart_retried_amount_without_smart_retries

Payment Distribution:
- Query Data:
  - payments_success_rate_distribution,
  - payments_success_rate_distribution_without_smart_retries,
  - payments_failure_rate_distribution,
  - payments_failure_rate_distribution_without_smart_retries
