### ISSUE TITLE
[BUG] Surcharge and 3DS routing issue

### ISSUE THREAD

**Issue by prajwalnl0** [juspay/hyperswitch-control-center#1509]
When Surcharge and 3DS Decision Manager routing is not configured, both `/routing/decision` and `/routing/decision/surcharge` returns 404 error

### Surcharge
![Image](https://github.com/user-attachments/assets/b31caafc-f864-4cb7-9003-e941d62f2c6b)
![Image](https://github.com/user-attachments/assets/4659a124-fa7c-4903-a5b1-ab8bff35a251)

### 3DS
![Image](https://github.com/user-attachments/assets/0798852e-63f9-42e9-80e2-3c8117d2c67b)
![Image](https://github.com/user-attachments/assets/319c23d7-07f4-4694-910c-49a5280918dd)

**Comment by hrithikesh026** [comment]
I believe this is expected behaviour.

**Comment by likhinbopanna** [comment]
@hrithikesh026 Why it should throw 404 on this , it could be empty array right ?

**Comment by hrithikesh026** [comment]
This is not a list endpoint. It returns a single object.

**Comment by muditbhutani** [comment]
@prajwalnl0 please close if resolved
