### ISSUE TITLE
[FEATURE] Add scroll for merchant, org and profile dropdowns

### ISSUE THREAD

**Issue by muditbhutani** [juspay/hyperswitch-control-center#1530]
In the profile dropdown only a limited number of profiles are visible and there is no scroll bar. This results in lack of visibility for the profiles that are not visible without scroll

To handle this we will add a scrollbar inside all three components: org, merchant and profile dropdown

The scrollbar should be visible only after the number of choices are so much that the base viewport is unable to accommodate them and subsequent profiles/merchants/orgs require scrolling

**Comment by Riddhiagrawal001** [comment]
Few more changes in the profile dropdown : 
- Please add a border in the dropdown as when zoomed in it merges with the home page card 
<img width="1623" alt="image" src="https://github.com/user-attachments/assets/aaa3bfc6-8d91-409e-926f-86513d7bdadc">

- Please also increase the width of the profile dropdown
