### ISSUE TITLE
Payment processed metric name bug

### ISSUE THREAD

**Issue by sagarnaikjuspay** [juspay/hyperswitch-control-center#1616]
<pre>
{
    "timeRange": {
        "startTime": "2024-07-31T18:30:00Z",
        "endTime": "2024-08-31T18:29:59Z"
    },
    "timeSeries": {
        "granularity": "G_ONEDAY"
    },
    "source": "BATCH",
    "metrics": [
        "sessionized_payment_processed_amount",
        "sessionized_payment_processed_count"
    ]
}
</pre>

<pre>
{
    "error": "Json deserialize error: unknown variant `sessionized_payment_processed_count`, expected one of `successful_smart_retries`, `total_smart_retries`, `smart_retried_amount`, `payment_intent_count`, `payments_success_rate`, `sessionized_successful_smart_retries`, `sessionized_total_smart_retries`, `sessionized_smart_retried_amount`, `sessionized_payment_intent_count`, `sessionized_payments_success_rate`, `sessionized_payment_processed_amount`, `sessionized_payments_distribution` at line 1 column 228"
}
</pre>

**Comment by tsdk02** [comment]
You will get both the payment_processed_amount and payment_processed_count from `sessionized_payment_processed_amount` metric itself. No need for separate metrics.
