### ISSUE TITLE
Payment success rate meta data is not showing up

### ISSUE THREAD

**Issue by sagarnaikjuspay** [juspay/hyperswitch-control-center#1617]
<pre>
{
    "timeRange": {
        "startTime": "2024-07-31T18:30:00Z",
        "endTime": "2024-08-31T18:29:59Z"
    },
    "timeSeries": {
        "granularity": "G_ONEDAY"
    },
    "source": "BATCH",
    "metrics": [
        "payment_success_rate"
    ]
}
</pre>

<pre>
 "metaData": [
        {
            "total_payment_processed_amount": 0,
            "total_payment_processed_amount_without_smart_retries": 0,
            "total_payment_processed_count": 0,
            "total_payment_processed_count_without_smart_retries": 0,
            "total_failure_reasons_count": 0,
            "total_failure_reasons_count_without_smart_retries": 0
        }
    ]
</pre>

**Comment by tsdk02** [comment]
The metric name here should be `sessionized_payments_success_rate` and not `payment_success_rate`.
Also, the api which should get called here is `/analytics/v2/metrics/payments` and not `/analytics/v1/metrics/payments`
