### ISSUE TITLE
Overview section Total Payments Processed is coming as empty

### ISSUE THREAD

**Issue by sagarnaikjuspay** [juspay/hyperswitch-control-center#1618]
<img width="985" alt="image" src="https://github.com/user-attachments/assets/62486daa-609c-4d7d-9692-7e23fb9186df">

<pre>
"queryData": [
        {
            "successful_smart_retries": null,
            "total_smart_retries": null,
            "smart_retried_amount": 0,
            "smart_retried_amount_without_smart_retries": 0,
            "payment_intent_count": null,
            "successful_payments": 45,
            "successful_payments_without_smart_retries": 45,
            "total_payments": 50,
            "payments_success_rate": 90.0,
            "payments_success_rate_without_smart_retries": 90.0,
            "payment_processed_amount": 708800,
            "payment_processed_count": 45,
            "payment_processed_amount_without_smart_retries": 708800,
            "payment_processed_count_without_smart_retries": 45,
            "payments_success_rate_distribution_without_smart_retries": null,
            "payments_failure_rate_distribution_without_smart_retries": null,
            "status": null,
            "currency": null,
            "profile_id": null,
            "connector": null,
            "auth_type": null,
            "payment_method": null,
            "payment_method_type": null,
            "card_network": null,
            "merchant_id": null,
            "card_last_4": null,
            "card_issuer": null,
            "error_reason": null,
            "time_range": {
                "start_time": "2024-06-30T18:30:01.000Z",
                "end_time": "2024-07-31T18:30:00.000Z"
            },
            "time_bucket": "2024-06-30 18:30:01"
        }
    ]
</pre>

**Comment by tsdk02** [comment]
Overview section Total Payments Processed should be taken from the metadata field.
Meta Data:
- total_payment_processed_amount
- total_payment_processed_count
- total_payment_processed_amount_without_smart_retries
- total_payment_processed_count_without_smart_retries
