### ISSUE TITLE
[CHORE] Permissions Change and user management change

### ISSUE THREAD

**Issue by Riddhiagrawal001** [juspay/hyperswitch-control-center#1623]
- [x] Check if old permission info api is using permissions from the api 
- [x] Check Home page credentials section is not shown in profile and check for the retrieve merchant account API 
- [x] Add enum for AccountRead and AccountWrite 
- [x] Change the merchant_details_manage , merchant_details_view , organization manage to account_read and account_write 
- [x] Change the type of user_role api in Recoil 
- [x] Update the places where recoil is used 
- [x] Integrate the new API for sidebar changes 
- [x] Integrate new module list API in Invite users page `[user/role/v2/{{role_id}}]` 
- [x] Update the Role description component accordingly 
- [x] User the `module/list` api to show non-accessible module 
- [ ] #1654

**Comment by ThisIsMani** [comment]
> Change the merchant_details_manage , merchant_details_view , organization manage to account_read and account_write


Let's not remove this currently. It's not a backward's compatible change.

FE can do it after BE new enum changes are deployed in sandbox and prod.
