### ISSUE TITLE
[REFACTOR] : Remove unused feature flags

### ISSUE THREAD

**Issue by JeevaRamu0104** [juspay/hyperswitch-control-center#515]
"production_access": false, replace it with is_live_mode
"home_page" replace it with is_live_mode
"switch_merchant": true, remove this feature flag
"user_management": true,  remove this feature flag
"test_processors": false,  replace it with is_live_mode
"verify_connector": true, remove this feature flag
"business_profile": true,  remove this feature flag
"generate_report": true, remove this feature flag
"oss_build":false, remove this feature flag
"magic_link": false, rename the magic_link to email
"forgot_password":true, use email feature flag
"mixpanel_sdk":false, remove the code and then remove this flag
"invite_multiple": false, check with 
[@PritishBudhiraja ] why its not enabled in prod
  "accept-invite": false, check with 
[@PritishBudhiraja ] why its not enabled in prod

**Comment by PritishBudhiraja** [comment]
`invite_multiple` - we can remove this flag as it was not their in prod previously. 
https://github.com/juspay/hyperswitch-control-center/pull/518
https://github.com/juspay/hyperswitch-control-center/pull/516
