### ISSUE TITLE
Demo checkout showing blank page even on 200 status code

### ISSUE THREAD

**Issue by JeevaRamu0104** [juspay/hyperswitch-control-center#663]
<img width="1728" alt="image" src="https://github.com/juspay/hyperswitch-control-center/assets/120017870/6b47e441-a6ef-4971-8017-e94deaaa2193">
<img width="1728" alt="image" src="https://github.com/juspay/hyperswitch-control-center/assets/120017870/033f5b28-462c-4098-b89d-08797a569dd9">
**Payload Passed**

{"client_secret":"pay_ZYlizJxNzXVXGtulO9kC_secret_AQy6PRjl3gw63nYZYJGh","return_url":"http://localhost:9000/dashboard/sdk","payment_method":"card","payment_method_data":{"card":{"card_number":"4242424242424242","card_exp_month":"01","card_exp_year":"2034","card_holder_name":"","card_cvc":"134","card_issuer":"","card_network":"Visa"}},"browser_info":{"user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","accept_header":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","language":"en-GB","color_depth":24,"screen_height":1117,"screen_width":1728,"time_zone":-330,"java_enabled":true,"java_script_enabled":true},"payment_type":"normal"}

- on status code 200 show **Go Payment Page**.

**Comment by PritishBudhiraja** [comment]
https://github.com/juspay/hyperswitch-control-center/pull/664
